# Generated by Django 3.1.5 on 2021-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAIFAIMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicableCategory3LightLevel', models.IntegerField(default=0)),
                ('applicableCategory3CategoryLightLevel', models.IntegerField(default=0)),
                ('taiMeasurePeriod', models.IntegerField(default=10)),
                ('taiLane1NumberOfVehicles', models.IntegerField(default=0)),
                ('taiLane2NumberOfVehicles', models.IntegerField(default=0)),
                ('measureTimestamp', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
