# Generated by Django 3.1.5 on 2021-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory1LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory2LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory4LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory5LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory6LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory7LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taifaimeasure',
            name='measureTimestamp',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
