# Generated by Django 3.1.5 on 2021-02-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20210208_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory1LightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory2LightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory3CategoryLightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory3LightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory4LightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory5LightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory6LightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory7LightLevel',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='measureTimestamp',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='taiLane1NumberOfVehicles',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='taiLane2NumberOfVehicles',
        ),
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='taiMeasurePeriod',
        ),
    ]
