# Generated by Django 3.1.5 on 2021-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20210208_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory1LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory2LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory3CategoryLightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory3LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory4LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory5LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory6LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='applicableCategory7LightLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='measureTimestamp',
            field=models.CharField(default=0, max_length=14),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='taiLane1NumberOfVehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='taiLane2NumberOfVehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='taiMeasurePeriod',
            field=models.IntegerField(default=10),
        ),
    ]
