# Generated by Django 3.1.5 on 2021-02-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20210208_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='taiMeasurePeriod',
        ),
        migrations.AlterField(
            model_name='taifaimeasure',
            name='measureTimestamp',
            field=models.IntegerField(default=0),
        ),
    ]
