# Generated by Django 3.1.5 on 2021-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20210209_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taifaimeasure',
            name='measureTimestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
