# Generated by Django 3.1.5 on 2021-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20210209_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taifaimeasure',
            name='applicableCategory3CategoryLightLevel',
        ),
        migrations.AddField(
            model_name='taifaimeasure',
            name='taiMeasurePeriod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='taifaimeasure',
            name='measureTimestamp',
            field=models.BigIntegerField(default=161287292402),
        ),
        migrations.AlterField(
            model_name='taifaimeasure',
            name='taiLane1NumberOfVehicles',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='taifaimeasure',
            name='taiLane2NumberOfVehicles',
            field=models.IntegerField(default=20),
        ),
    ]
