# Generated by Django 3.1.5 on 2021-02-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20210209_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taifaimeasure',
            old_name='measureTimestamp',
            new_name='measure_timestamp',
        ),
    ]
